const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  branch: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Branch',
    required: true
  },
  type: {
    type: String,
    enum: [
      'order', 'payment', 'system', 'kitchen', 'memo', 'task',
      // System-generated alert types
      'payment_failure', 'revenue_drop', 'unpaid_tables',
      'inventory_stockout', 'order_edit_abuse', 'table_release_abuse', 'coupon_abuse'
    ],
    required: true
  },
  category: {
    type: String,
    enum: [
      'manual',      // Manually created by admin
      'system',      // System-generated
      'automatic'    // Auto-generated by services
    ],
    default: 'manual'
  },
  severity: {
    type: String,
    enum: ['info', 'warning', 'critical'],
    default: 'warning'
  },
  title: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },
  isRead: {
    type: Boolean,
    default: false
  },
  isDismissed: {
    type: Boolean,
    default: false
  },
  isSystemGenerated: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin'
  },
  relatedId: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: 'onModel'
  },
  onModel: {
    type: String,
    enum: ['Order', 'Table', 'Payment', 'Memo', 'Coupon', 'MenuItem']
  },
  actionUrl: String,
  
  // System alert specific fields
  metadata: {
    metric: String,        // e.g., 'revenue', 'unpaid_tables', 'order_edits'
    value: Number,         // Current value
    threshold: Number,     // Threshold that triggered alert
    previousValue: Number, // For trend analysis
    failureCount: Number,  // For payment failures
    affectedRecords: [mongoose.Schema.Types.ObjectId] // Related order/table IDs
  },
  
  readAt: Date,
  dismissedAt: Date,
  resolvedAt: Date,
  isResolved: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

// Indexes for performance
alertSchema.index({ branch: 1, isRead: 1 });
alertSchema.index({ branch: 1, isDismissed: 1 });
alertSchema.index({ branch: 1, isSystemGenerated: 1 });
alertSchema.index({ branch: 1, severity: 1 });
alertSchema.index({ createdAt: -1 });
alertSchema.index({ branch: 1, createdAt: -1 });
alertSchema.index({ isResolved: 1, createdAt: -1 });

module.exports = mongoose.model('Alert', alertSchema);
